# Naive Bayes Project Tutorial


In [2]:
%%capture

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline 

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

from sklearn import metrics

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
data = pd.read_csv('https://raw.githubusercontent.com/4GeeksAcademy/naive-bayes-project-tutorial/main/playstore_reviews_dataset.csv')

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   package_name  891 non-null    object
 1   review        891 non-null    object
 2   polarity      891 non-null    int64 
dtypes: int64(1), object(2)
memory usage: 21.0+ KB


In [6]:
data.head()

package_name                                             review  \
0  com.facebook.katana   privacy at least put some option appear offli...   
1  com.facebook.katana   messenger issues ever since the last update, ...   
2  com.facebook.katana   profile any time my wife or anybody has more ...   
3  com.facebook.katana   the new features suck for those of us who don...   
4  com.facebook.katana   forced reload on uploading pic on replying co...   

   polarity  
0         0  
1         0  
2         0  
3         0  
4         0

In [7]:
data=data.drop(columns='package_name')

In [8]:
data.head()

review  polarity
0   privacy at least put some option appear offli...         0
1   messenger issues ever since the last update, ...         0
2   profile any time my wife or anybody has more ...         0
3   the new features suck for those of us who don...         0
4   forced reload on uploading pic on replying co...         0

In [9]:
#pasar todo a minuscula 
#strip espacios de mas 

data['review'] = data['review'].str.strip().str.lower()

In [10]:
data['polarity'].value_counts()

0    584
1    307
Name: polarity, dtype: int64

In [11]:
#paso 2

X=data['review']
y=data['polarity']

In [12]:
X_train, X_test, Y_train, Y_test = train_test_split(X,y, stratify=y, test_size=0.25, random_state=42) 

In [13]:
#paso 3

# Vectorize text reviews to numbers
vec = CountVectorizer(stop_words='english')

#stop_words son palabras que no son necesarias en un analisis de texto, por ejemplo un 'the', 'and'
#para que no las tenga en cuenta

In [14]:
X_train = vec.fit_transform(X_train).toarray()
X_test = vec.transform(X_test).toarray()

In [15]:
#cada columna es una palabra

X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [16]:
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [17]:
len(X_train)

668

In [18]:
len(X_train[0])

3161

In [19]:
len(X_train[1])

3161

In [20]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train, Y_train)

MultinomialNB()

In [21]:
model.score(X_test,Y_test)

0.8565022421524664

In [22]:
#predicciones

model.predict(vec.transform(['I hate with my heart this app ']))

#deberia dar 0, ya que 0 es negativo

array([0], dtype=int64)

In [23]:
model.predict(vec.transform(['Love this app simply awesome!']))

#deberia dar 1, ya que 1 es positivo

array([1], dtype=int64)

In [24]:
string = '''
I love Google Play Store. The website and mobile site are both very easy to maneuver. I think it's great that Google has so many free applications available. I review for Google often and they usually send me an update to say thank you. I use Google Play often and will continue to do so. #GooglePlayStore #Techie #DigitalArt created by yours truly. Follow me on IG to see more original content. #MKR #IamMimisMusic Google Play Store
'''

In [25]:
model.predict(vec.transform([string]))


array([0], dtype=int64)

In [26]:
model.predict(vec.transform(['normal']))


array([1], dtype=int64)

In [27]:
#si el comentario es breve y claro funciona bien pero si es largo y confuso no
#tampoco funciona bien si es intermedio 


In [28]:
#!pip install pickle

ERROR: Could not find a version that satisfies the requirement pickle (from versions: none)
ERROR: No matching distribution found for pickle
You should consider upgrading via the 'C:\Users\cindy\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.


In [30]:
import pickle


In [31]:
#paso 4
filename = 'nb_model.sav'
pickle.dump(model, open(filename,'wb'))